name: "Quils in Space"
highlighter: rouge
markdown: kramdown
exclude:
  - node_modules
  - vendor

navigation:
  - text: Home
    url: /index.html
    group: home
  - text: Articles
    url: /blog
    group: blog
  - text: Art
    url: https://www.instagram.com/q.teatime/
    group: art
