name: "Quils in Space"
highlighter: rouge
markdown: kramdown
exclude:
  - node_modules
  - vendor

navigation:
  - text: Home
    url: /index.html
  - text: Articles
    url: /blog
  - text: Art
    url: https://art.robotlolita.me/
