name: "Quils in Space"
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
exclude:
- node_modules
- vendor

navigation:
- text: Blog
  url: /index.html
- text: Art
  url: http://art.robotlolita.me/
- text: About
  url: /about/index.html
